function generate(
  schematic: Schematic,
  scale: Slider<{ min: 0.05; max: 0.5; step: 0.05; default: 0.125 }>,
  tag: string,
): {
  mcfunction: string;
  commands: number;
} {
  const tagName = tag || 'hologram';
  const f = Mcfunction.builder()
    .comment('Tiny block_display hologram - generated by Flow')
    .comment('Paste into a datapack function and run it where the hologram should appear.')
    .killTagged(tagName);

  const LIMIT = 4000;
  let count = 0;
  for (const b of schematic.blocks()) {
    if (count >= LIMIT) {
      f.comment('... truncated at ' + LIMIT + ' blocks');
      break;
    }
    // block_display Name takes the bare id; blockstate properties are dropped.
    const name = b.name.split('[')[0];
    f.summonBlockDisplay(
      { x: b.x * scale, y: b.y * scale + 1, z: b.z * scale },
      name,
      scale,
      tagName
    );
    count++;
  }

  return { mcfunction: f.toString(), commands: count };
}
