/**
 * Carbon 1.1 assembler — a self-contained TypeScript port of tony-ist's reference
 * assembler (github.com/tony-ist/carbon1dot1-assembler), verified BYTE-FOR-BYTE
 * against that assembler's own output (see carbon.test.ts, fixtures generated by
 * building and running the Rust reference).
 *
 * Carbon 1.1 is an 8-bit, ACC-based, pure-Harvard Minecraft redstone CPU (8-tick
 * clock, 5-stage pipeline). One operand, 3 bits; opcode 5 bits.
 *
 * Encoding (hand-rolled — the generic kit's regular driver can't express it):
 *   - Base word: (opcode << 3) | operand3, where the single register / port /
 *     condition operand is merged into the low 3 bits.
 *   - LIM / CAL / PSI / BSL / BSR append a raw immediate byte after the word.
 *   - BRC is THREE bytes: [word|cond, floor(addr/128), (addr % 128) - 2]. The
 *     `- 2` is the pipeline branch-offset the reference applies.
 *   - An implicit HLT (0xF0) is appended after the program (the reference's
 *     name-mangling pass does this).
 *
 * Quirk faithfully reproduced: label addresses live in a separate "pc space"
 * (the reference's lower_labels pass) that counts immediate / $-port / label
 * operands as +1 byte but registers / conditions as +0 — even though a $-port
 * operand emits NO extra byte. So $-port instructions before a label inflate
 * that label's address by one. We replicate this so branch targets match.
 */

import { AssembleError } from '../kit.js';

export { AssembleError } from '../kit.js';

/** Opcode numbers (5-bit). 14 is an intentional hole — LIM is pinned to 0b01111. */
export const CARBON_OPCODES: Record<string, number> = {
  NOP: 0, INC: 1, DEC: 2, ADD: 3, ADR: 4, NEG: 5, SUB: 6, BSB: 7, CMP: 8, BOR: 9,
  AND: 10, XOR: 11, BSL: 12, BSR: 13, LIM: 15, RST: 16, RLD: 17, MST: 18, MLD: 19,
  CAL: 20, RET: 21, BRC: 22, JID: 23, PSH: 24, POP: 25, PST: 26, PSI: 27, PLD: 28,
  PRD: 29, HLT: 30, FLS: 31,
};

/** Branch / predicate condition codes (low 3 bits). */
export const CARBON_CONDITIONS: Record<string, number> = {
  JMP: 0, EVEN: 1, EQ: 2, NEQ: 3, GT: 4, LT: 5, GTEQ: 6, LTEQ: 7,
};

type OperandKind = 'reg' | 'imm' | 'addr' | 'cond' | 'label';

/** Operand shapes per mnemonic, in source order (mirrors parser.lalrpop). */
const FORMS: Record<string, OperandKind[]> = {
  NOP: [], RET: [], PSH: [], POP: [], HLT: [], FLS: [],
  INC: ['reg'], DEC: ['reg'], ADD: ['reg'], ADR: ['reg'], NEG: ['reg'], SUB: ['reg'],
  BSB: ['reg'], CMP: ['reg'], BOR: ['reg'], AND: ['reg'], XOR: ['reg'],
  RST: ['reg'], RLD: ['reg'], MST: ['reg'], MLD: ['reg'], JID: ['reg'],
  BSL: ['imm'], BSR: ['imm'],
  LIM: ['reg', 'imm'],
  CAL: ['label'],
  BRC: ['cond', 'label'], PRD: ['cond', 'label'],
  PST: ['addr'], PSI: ['addr', 'imm'], PLD: ['addr'],
};

interface Line {
  kind: 'instr' | 'label' | 'data';
  mnemonic?: string;
  operands?: string[];
  name?: string;       // label name (with leading '.')
  data?: number[];     // data-string bytes
  raw: string;
}

/** Strip a `// …` / `/ …` comment, ignoring slashes inside a "…" string. */
function stripComment(line: string): string {
  let inStr = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (c === '"') inStr = !inStr;
    else if (c === '/' && !inStr) return line.slice(0, i);
  }
  return line;
}

function parseLines(src: string): Line[] {
  const out: Line[] = [];
  for (const rawLine of src.split('\n')) {
    const raw = rawLine;
    const stripped = stripComment(rawLine).trim();
    if (!stripped) continue;

    if (stripped === 'FUNC' || stripped.startsWith('FUNC ') || stripped === 'END') {
      throw new AssembleError(
        'FUNC/END subroutine blocks are not supported by this example assembler — ' +
          'use plain labels + CAL/BRC instead.',
      );
    }

    // Data string: "…" → its UTF-8 bytes.
    if (stripped.startsWith('"')) {
      const last = stripped.lastIndexOf('"');
      if (last <= 0) throw new AssembleError(`Unterminated data string: ${raw}`);
      const text = stripped.slice(1, last);
      out.push({ kind: 'data', data: Array.from(new TextEncoder().encode(text)), raw });
      continue;
    }

    const tokens = stripped.split(/\s+/);
    // A lone `.label` token defines a label here.
    if (tokens.length === 1 && tokens[0].startsWith('.')) {
      out.push({ kind: 'label', name: tokens[0], raw });
      continue;
    }

    out.push({ kind: 'instr', mnemonic: tokens[0].toUpperCase(), operands: tokens.slice(1), raw });
  }
  return out;
}

/** Bytes an instruction occupies in the reference's pc-space (for label addrs). */
function pcSize(mnemonic: string, form: OperandKind[]): number {
  if (mnemonic === 'BRC') return 3;
  // +1 base; immediate / $-port / label operands add a byte, registers/conds don't.
  return form.reduce((n, k) => n + (k === 'imm' || k === 'addr' || k === 'label' ? 1 : 0), 1);
}

function formFor(mnemonic: string, raw: string): OperandKind[] {
  const form = FORMS[mnemonic];
  if (!form) throw new AssembleError(`Unknown instruction "${mnemonic}" (${raw.trim()})`);
  return form;
}

/** Resolve one operand token to its numeric value given its expected kind. */
function resolveOperand(
  kind: OperandKind,
  token: string,
  labels: Record<string, number>,
  raw: string,
): number {
  switch (kind) {
    case 'reg': {
      if (!/^[rR]\d$/.test(token)) throw new AssembleError(`Expected a register (rN), got "${token}" — ${raw.trim()}`);
      return parseInt(token.slice(1), 10);
    }
    case 'addr': {
      if (!/^\$\d$/.test(token)) throw new AssembleError(`Expected a port ($N), got "${token}" — ${raw.trim()}`);
      return parseInt(token.slice(1), 10);
    }
    case 'imm': {
      if (!/^\d+$/.test(token)) throw new AssembleError(`Expected an immediate, got "${token}" — ${raw.trim()}`);
      const v = parseInt(token, 10);
      if (v > 255) throw new AssembleError(`Immediate ${v} out of range (0–255) — ${raw.trim()}`);
      return v;
    }
    case 'cond': {
      const c = CARBON_CONDITIONS[token.toUpperCase()];
      if (c === undefined) throw new AssembleError(`Unknown condition "${token}" — ${raw.trim()}`);
      return c;
    }
    case 'label': {
      if (!token.startsWith('.')) throw new AssembleError(`Expected a label (.name), got "${token}" — ${raw.trim()}`);
      const addr = labels[token];
      if (addr === undefined) throw new AssembleError(`Reference to undefined label "${token}" — ${raw.trim()}`);
      return addr;
    }
  }
}

/** Assemble a Carbon 1.1 program into machine-code bytes (0–255). */
export function assemble(src: string): number[] {
  const lines = parseLines(src);

  // Pass 1 — label addresses in the reference's pc-space (wraps at 256).
  const labels: Record<string, number> = {};
  let pc = 0;
  for (const line of lines) {
    if (line.kind === 'label') {
      labels[line.name!] = pc;
    } else if (line.kind === 'data') {
      pc = (pc + line.data!.length) & 0xff;
    } else {
      const form = formFor(line.mnemonic!, line.raw);
      pc = (pc + pcSize(line.mnemonic!, form)) & 0xff;
    }
  }

  // Pass 2 — emit bytes.
  const bytes: number[] = [];
  for (const line of lines) {
    if (line.kind === 'label') continue;
    if (line.kind === 'data') {
      bytes.push(...line.data!);
      continue;
    }
    const mnemonic = line.mnemonic!;
    const form = formFor(mnemonic, line.raw);
    const ops = line.operands!;
    if (ops.length !== form.length) {
      throw new AssembleError(
        `"${mnemonic}" expects ${form.length} operand(s), got ${ops.length} — ${line.raw.trim()}`,
      );
    }

    let word = (CARBON_OPCODES[mnemonic] << 3) & 0xff;
    let pushedWord = false;
    form.forEach((kind, i) => {
      const value = resolveOperand(kind, ops[i], labels, line.raw);
      if (kind === 'reg' || kind === 'addr' || kind === 'cond') {
        word = (word | value) & 0xff; // merge into the low 3 bits of the opword
        pushedWord = true;
        bytes.push(word);
      } else {
        // immediate-like (imm or resolved label)
        const a = value & 0xff;
        if (mnemonic === 'BRC') {
          bytes.push(Math.floor(a / 128) & 0xff);
          bytes.push((((a % 128) - 2) + 256) & 0xff); // pipeline branch offset, u8-wrapped
        } else {
          if (!pushedWord) {
            bytes.push(word);
            pushedWord = true;
          }
          bytes.push(a);
        }
      }
    });
    if (!pushedWord) bytes.push(word);
  }

  // Implicit terminating HLT, exactly like the reference's name-mangling pass.
  bytes.push((CARBON_OPCODES.HLT << 3) & 0xff);
  return bytes;
}

/** Render bytes as uppercase two-char hex (matches the other example helpers). */
export function toHex(bytes: number[]): string[] {
  return bytes.map((b) => b.toString(16).toUpperCase().padStart(2, '0'));
}
